// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mWsxNu6bNJUjXxTj6j5WLx
// Component: qXUK3qtvgZPB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import NavBar from "../../NavBar"; // plasmic-import: if0HoxvimUSz/component
import { CartProvider } from "../../medusa/CartProvider"; // plasmic-import: t5iYwTjkrz3s/codeComponent
import CartItem from "../../CartItem"; // plasmic-import: T7FuMDAcScL8/component
import Button from "../../Button"; // plasmic-import: Ddzk5l-7sQtW/component
import Separator from "../../Separator"; // plasmic-import: HdBnnmjiwAbR/component
import Footer from "../../Footer"; // plasmic-import: SeObnkyrmQ01/component

import { useScreenVariants as useScreenVariantsbpQaJqznhH0X } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: bpQAJqznhH0x/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mWsxNu6bNJUjXxTj6j5WLx/projectcss
import sty from "./PlasmicCart.module.css"; // plasmic-import: qXUK3qtvgZPB/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: tLfoPFexMQ-Z/icon
import Secure2Icon from "./icons/PlasmicIcon__Secure2"; // plasmic-import: G5gMoQJ5E2iM/icon

createPlasmicElementProxy;

export type PlasmicCart__VariantMembers = {
  empty: "empty";
};
export type PlasmicCart__VariantsArgs = {
  empty?: SingleBooleanChoiceArg<"empty">;
};
type VariantPropType = keyof PlasmicCart__VariantsArgs;
export const PlasmicCart__VariantProps = new Array<VariantPropType>("empty");

export type PlasmicCart__ArgsType = {
  slot?: React.ReactNode;
  slot3?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCart__ArgsType;
export const PlasmicCart__ArgProps = new Array<ArgPropType>("slot", "slot3");

export type PlasmicCart__OverridesType = {
  root?: Flex__<"div">;
  navBar?: Flex__<typeof NavBar>;
  cartProvider?: Flex__<typeof CartProvider>;
  section?: Flex__<"section">;
  cartItem?: Flex__<typeof CartItem>;
  separator?: Flex__<typeof Separator>;
  svg?: Flex__<"svg">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultCartProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCart__RenderFunc(props: {
  variants: PlasmicCart__VariantsArgs;
  args: PlasmicCart__ArgsType;
  overrides: PlasmicCart__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "empty",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.empty
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbpQaJqznhH0X()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicCart.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicCart.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicCart.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicCart.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicCart.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicCart.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root,
            { [sty.rootempty]: hasVariant($state, "empty", "empty") }
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar, {
              [sty.navBarempty]: hasVariant($state, "empty", "empty")
            })}
            filled={hasVariant($state, "empty", "empty") ? true : undefined}
          />

          <CartProvider
            data-plasmic-name={"cartProvider"}
            data-plasmic-override={overrides.cartProvider}
            className={classNames("__wab_instance", sty.cartProvider)}
          >
            <DataCtxReader__>
              {$ctx => (
                <Stack__
                  as={"section"}
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.section, {
                    [sty.sectionempty]: hasVariant($state, "empty", "empty")
                  })}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ynDtd, {
                      [sty.freeBoxempty__ynDtDan6Yl]: hasVariant(
                        $state,
                        "empty",
                        "empty"
                      )
                    })}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___4KO4,
                        {
                          [sty.freeBoxempty___4KO4An6Yl]: hasVariant(
                            $state,
                            "empty",
                            "empty"
                          )
                        }
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a0Lbm,
                          {
                            [sty.textempty__a0Lbman6Yl]: hasVariant(
                              $state,
                              "empty",
                              "empty"
                            )
                          }
                        )}
                      >
                        {hasVariant($state, "empty", "empty") ? (
                          "Looks like your bag is empty"
                        ) : (
                          <React.Fragment>
                            {(() => {
                              try {
                                return `Your bag (${$ctx.cart.items.length})`;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Your bag";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        )}
                      </div>
                      {(_par =>
                        !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                        (() => {
                          try {
                            return $ctx.cart.items;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return [];
                            }
                            throw e;
                          }
                        })()
                      ).map((__plasmic_item_0, __plasmic_idx_0) => {
                        const currentItem = __plasmic_item_0;
                        const currentIndex = __plasmic_idx_0;
                        return (
                          <CartItem
                            data-plasmic-name={"cartItem"}
                            data-plasmic-override={overrides.cartItem}
                            className={classNames(
                              "__wab_instance",
                              sty.cartItem,
                              {
                                [sty.cartItemempty]: hasVariant(
                                  $state,
                                  "empty",
                                  "empty"
                                )
                              }
                            )}
                            imgUrl={currentItem.thumbnail}
                            itemQuantity={(() => {
                              try {
                                return currentItem.quantity;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 10;
                                }
                                throw e;
                              }
                            })()}
                            key={currentIndex}
                            productVariant={(() => {
                              try {
                                return currentItem.variant;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                            title={currentItem.title}
                          />
                        );
                      })}
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ooUjg,
                          {
                            [sty.freeBoxempty__ooUjgan6Yl]: hasVariant(
                              $state,
                              "empty",
                              "empty"
                            )
                          }
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f4C1K,
                            {
                              [sty.textempty__f4C1Kan6Yl]: hasVariant(
                                $state,
                                "empty",
                                "empty"
                              )
                            }
                          )}
                        >
                          {
                            "If you have an account, please sign in to see items you previously added."
                          }
                        </div>
                        <Button
                          colors={"black"}
                          rounded={true}
                          size={"large"}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rYkyt
                            )}
                          >
                            {"Login"}
                          </div>
                        </Button>
                        <Button
                          colors={"white"}
                          rounded={true}
                          submitsForm={true}
                        >
                          {"Continue shopping"}
                        </Button>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__ffVk2,
                        {
                          [sty.freeBoxempty__ffVk2An6Yl]: hasVariant(
                            $state,
                            "empty",
                            "empty"
                          )
                        }
                      )}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3Uitw,
                          {
                            [sty.freeBoxempty___3Uitwan6Yl]: hasVariant(
                              $state,
                              "empty",
                              "empty"
                            )
                          }
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__da2Cl,
                            {
                              [sty.textempty__da2Clan6Yl]: hasVariant(
                                $state,
                                "empty",
                                "empty"
                              )
                            }
                          )}
                        >
                          {"Order Summary"}
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mIgx4,
                            {
                              [sty.freeBoxempty__mIgx4An6Yl]: hasVariant(
                                $state,
                                "empty",
                                "empty"
                              )
                            }
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__swjRu
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__b81O7,
                                {
                                  [sty.freeBoxempty__b81O7An6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___709At,
                                  {
                                    [sty.textempty___709ATan6Yl]: hasVariant(
                                      $state,
                                      "empty",
                                      "empty"
                                    )
                                  }
                                )}
                              >
                                {hasVariant($state, "empty", "empty") ? (
                                  "Subtotal (1)"
                                ) : (
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return `Subtotal (${$ctx.cart.items.length})`;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Subtotal (0)";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                )}
                              </div>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___3Dr6P,
                                {
                                  [sty.freeBoxempty___3Dr6Pan6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___6MPnX,
                                  {
                                    [sty.textempty___6MPnXan6Yl]: hasVariant(
                                      $state,
                                      "empty",
                                      "empty"
                                    )
                                  }
                                )}
                              >
                                {hasVariant($state, "empty", "empty") ? (
                                  "$88.99"
                                ) : (
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return (
                                          "$" +
                                          ($ctx.cart.subtotal / 100).toFixed(2)
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "$0.00";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                )}
                              </div>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__eWkl3
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mTyS,
                                {
                                  [sty.textempty__mTySan6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              {"Estimated Shipping (free over $49)"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__zl3AQ,
                                {
                                  [sty.freeBoxempty__zl3AQan6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              {renderPlasmicSlot({
                                defaultContents: hasVariant(
                                  $state,
                                  "empty",
                                  "empty"
                                )
                                  ? "FREE"
                                  : "FREE",
                                value: args.slot,
                                className: classNames(sty.slotTargetSlot, {
                                  [sty.slotTargetSlotempty]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                })
                              })}
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__hfNd3
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nmdOi,
                                {
                                  [sty.textempty__nmdOian6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              {"Estimated Tax"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__lw2Sj,
                                {
                                  [sty.freeBoxempty__lw2Sjan6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__r5Xsl,
                                  {
                                    [sty.textempty__r5Xslan6Yl]: hasVariant(
                                      $state,
                                      "empty",
                                      "empty"
                                    )
                                  }
                                )}
                              >
                                <React.Fragment>
                                  {(() => {
                                    try {
                                      return (
                                        "$" +
                                        (
                                          $ctx.cart.item_tax_total / 100
                                        ).toFixed(2)
                                      );
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return "-";
                                      }
                                      throw e;
                                    }
                                  })()}
                                </React.Fragment>
                              </div>
                            </div>
                          </div>
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__v2Yce,
                              {
                                [sty.buttonempty__v2Ycean6Yl]: hasVariant(
                                  $state,
                                  "empty",
                                  "empty"
                                )
                              }
                            )}
                            colors={"link"}
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___0PUk
                              )}
                            >
                              {"Have a promo code?"}
                            </div>
                          </Button>
                          <Separator
                            data-plasmic-name={"separator"}
                            data-plasmic-override={overrides.separator}
                            className={classNames(
                              "__wab_instance",
                              sty.separator
                            )}
                            dark={true}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__lsNq3,
                              {
                                [sty.freeBoxempty__lsNq3An6Yl]: hasVariant(
                                  $state,
                                  "empty",
                                  "empty"
                                )
                              }
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gq7W6,
                                {
                                  [sty.textempty__gq7W6An6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              {"Estimated Total"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__uhiHm,
                                {
                                  [sty.freeBoxempty__uhiHman6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__tIzqJ,
                                  {
                                    [sty.textempty__tIzqJan6Yl]: hasVariant(
                                      $state,
                                      "empty",
                                      "empty"
                                    )
                                  }
                                )}
                              >
                                {hasVariant($state, "empty", "empty") ? (
                                  "$88.99"
                                ) : (
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return (
                                          "$" +
                                          ($ctx.cart.total / 100).toFixed(2)
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "$0.00";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                )}
                              </div>
                            </div>
                          </div>
                          {(hasVariant($state, "empty", "empty") ? true : false)
                            ? renderPlasmicSlot({
                                defaultContents: (
                                  <Button
                                    className={classNames(
                                      "__wab_instance",
                                      sty.button__nj3Su
                                    )}
                                    colors={"blue"}
                                    rounded={true}
                                    size={"large"}
                                    submitsForm={true}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__nQh9Y
                                      )}
                                    >
                                      {"Checkout"}
                                    </div>
                                  </Button>
                                ),
                                value: args.slot3
                              })
                            : null}
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aOWkV,
                              {
                                [sty.freeBoxempty__aOWkVan6Yl]: hasVariant(
                                  $state,
                                  "empty",
                                  "empty"
                                )
                              }
                            )}
                          >
                            <Secure2Icon
                              data-plasmic-name={"svg"}
                              data-plasmic-override={overrides.svg}
                              className={classNames(projectcss.all, sty.svg)}
                              role={"img"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2FYvk,
                                {
                                  [sty.textempty___2FYvKan6Yl]: hasVariant(
                                    $state,
                                    "empty",
                                    "empty"
                                  )
                                }
                              )}
                            >
                              {"Secure"}
                            </div>
                          </Stack__>
                        </Stack__>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yjjoh,
                          {
                            [sty.freeBoxempty__yjjohan6Yl]: hasVariant(
                              $state,
                              "empty",
                              "empty"
                            )
                          }
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__uz2Xc)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"48px"}
                          src={{
                            src: "/plasmic/copy_of_medusa_js_plasmic_demo_store/images/visa.svg",
                            fullWidth: 210,
                            fullHeight: 150,
                            aspectRatio: 1.4
                          }}
                        />

                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___34Za)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"48px"}
                          src={{
                            src: "/plasmic/copy_of_medusa_js_plasmic_demo_store/images/americanExpress.svg",
                            fullWidth: 210,
                            fullHeight: 150,
                            aspectRatio: 1.4
                          }}
                        />

                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__z6ZyS)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"48px"}
                          src={{
                            src: "/plasmic/copy_of_medusa_js_plasmic_demo_store/images/discover.svg",
                            fullWidth: 210,
                            fullHeight: 150,
                            aspectRatio: 1.4
                          }}
                        />

                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__eFwA8)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"48px"}
                          src={{
                            src: "/plasmic/copy_of_medusa_js_plasmic_demo_store/images/mastercard.svg",
                            fullWidth: 213,
                            fullHeight: 150,
                            aspectRatio: 1.416667
                          }}
                        />
                      </Stack__>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__f7V5S, {
                      [sty.freeBoxempty__f7V5San6Yl]: hasVariant(
                        $state,
                        "empty",
                        "empty"
                      )
                    })}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__pbNnV)}
                      displayHeight={"32px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={
                        "https://www.patagonia.com/on/demandware.static/-/Library-Sites-PatagoniaShared/default/dw4b201dc8/images/for-the-planet.png"
                      }
                    />

                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1I5C0
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uhqxw
                        )}
                      >
                        {
                          "1% of your purchase will go to a grassroot organization."
                        }
                      </div>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__gXm9C
                        )}
                        colors={"link"}
                        submitsForm={true}
                      >
                        {"Learn more"}
                      </Button>
                    </Stack__>
                  </Stack__>
                </Stack__>
              )}
            </DataCtxReader__>
          </CartProvider>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "cartProvider",
    "section",
    "cartItem",
    "separator",
    "svg",
    "footer"
  ],
  navBar: ["navBar"],
  cartProvider: ["cartProvider", "section", "cartItem", "separator", "svg"],
  section: ["section", "cartItem", "separator", "svg"],
  cartItem: ["cartItem"],
  separator: ["separator"],
  svg: ["svg"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  cartProvider: typeof CartProvider;
  section: "section";
  cartItem: typeof CartItem;
  separator: typeof Separator;
  svg: "svg";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCart__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCart__VariantsArgs;
    args?: PlasmicCart__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCart__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCart__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCart__ArgProps,
          internalVariantPropNames: PlasmicCart__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCart__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCart";
  } else {
    func.displayName = `PlasmicCart.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "mWsxNu6bNJUjXxTj6j5WLx"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicCart = Object.assign(
  // Top-level PlasmicCart renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    cartProvider: makeNodeComponent("cartProvider"),
    section: makeNodeComponent("section"),
    cartItem: makeNodeComponent("cartItem"),
    separator: makeNodeComponent("separator"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCart
    internalVariantProps: PlasmicCart__VariantProps,
    internalArgProps: PlasmicCart__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Shopping Cart",
      description:
        "Congue pulvinar scelerisque vestibulum senectus ullamcorper ac sem justo odio adipiscing volutpat nam a amet quam facilisi parturient parturient et id parturient per.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCart;
/* prettier-ignore-end */
